### ISSUE TITLE
ElasticSearchOutput stops working if Elasticsearch server restarts

### ISSUE THREAD

**Issue by ianneub** [mozilla-services/heka#1008]
When using the `ElasticSearchOutput`: if the Elasticsearch server goes down for some reason, and then comes back up, the `ElasticSearchOutput` will be hung and will not send any more messages to the Elasticsearch server, until `hekad` is restarted. At which point any messages that are inside `hekad` will be lost. Also note, at least in this example the `HttpListenInput` will continue to accept new messages.

Running a heka server from commit `135bcfd25db48253e01c5b085b4f5912fa2a6fae` and Elasticsearch `1.1.2` or `1.3.1` with this config:

``` toml
[HttpListenInput]
address = "0.0.0.0:4881"

[ESJsonEncoder]
index = "hekad-%{2006.01.02}"
es_index_from_timestamp = true
type_name = "%{Type}"

[ElasticSearchOutput]
message_matcher = "Logger == 'HttpListenInput'"
server = "http://localhost:9200"
flush_interval = 5000
flush_count = 10
encoder = "ESJsonEncoder"
```

To reproduce:

```
curl -XPOST 'http://localhost:4881' -d 'asdf1'
curl -XPOST 'http://localhost:4881' -d 'asdf2'
curl -XPOST 'http://localhost:4881' -d 'asdf3'
curl -XPOST 'http://localhost:9200/_search?q=*'
```

You should see 3 records returned.

Now if you restart the Elasticsearch server, and run these:

```
curl -XPOST 'http://localhost:4881' -d 'asdf4'
curl -XPOST 'http://localhost:4881' -d 'asdf5'
curl -XPOST 'http://localhost:4881' -d 'asdf6'
curl -XPOST 'http://localhost:4881' -d 'asdf7'
curl -XPOST 'http://localhost:4881' -d 'asdf8'
curl -XPOST 'http://localhost:4881' -d 'asdf9'
curl -XPOST 'http://localhost:9200/_search?q=*'
```

You will still see only 3 records in Elasticsearch (even after waiting for the `flush_interval`).
