### ISSUE TITLE
Config files should support environment variables

### ISSUE THREAD

**Issue by ianneub** [mozilla-services/heka#1023]
Heka's toml config files should support environment variables that will be substituted at run time.

For example:

``` toml
[AMQPInput]
url = "amqp://%ENV[user]%:%ENV[password]%@rabbitmq/"
exchange = "testout"
exchangeType = "fanout"
```

or:

``` toml
[AMQPInput]
url = "amqp://$USER:$PASSWORD@rabbitmq/"
exchange = "testout"
exchangeType = "fanout"
```
