### ISSUE TITLE
LogstreamerInput doesn't remember log file position

### ISSUE THREAD

**Issue by arctica** [mozilla-services/heka#1106]
I have set up heka for the first time with some simple LogstreamerInput that picks up json encoded log lines from a directory, runs those through a sandbox json decoder, encodes them for ElasticSearch and then outputs to stdout via LogOutput.

It reads, decodes, encodes and outputs the log entries just fine but every time I restart heka, it processes the same logs again. It seems that it has trouble remembering the position in the journal.

Using strace, I could see that heka tries to open() the journal under /var/cache/hekad/logstreamer/json_log which does not exist of course. But it never tries to create the file or write to it.

Config:

``` toml
[hekad]
maxprocs = 2

[json_log]
type = "LogstreamerInput"
log_directory = "/var/log/json"
decoder = "JsonDecoder"
file_match = '.*\.log\.?(?P<Index>\d+)?(\.gz)?'
priority = ["^Index"]

[JsonDecoder]
type = "SandboxDecoder"
script_type = "lua"
filename = "/etc/heka//json.lua"

[LogOutput]
message_matcher = "TRUE"
encoder = "ESJsonEncoder"

[ESJsonEncoder]
index = "%{Type}-%{2006.01.02}"
es_index_from_timestamp = true
type_name = "%{Type}"
```
