### ISSUE TITLE
TLS with HttpOutput: Unrecognized struct kind: [ptr]

### ISSUE THREAD

**Issue by markabey** [mozilla-services/heka#1163]
If I have a HttpOutput and try to set the tls settings on it, heka won't start.
It prints the following error:

 Loading: [HttpOutput]
 Can't load config for HttpOutput: Unrecognized struct kind: [ptr]
 Error reading config: 1 errors loading plugins

The tls section works correctly with TCPOutput.

example config:

``` toml
[HttpOutput]
 message_matcher = 'Type !~ /^heka\./'
 address = "https://host.domain:12000/url"
 encoder = "RstEncoder"

    [HttpOutput.tls]
     insecure_skip_verify = true
```

Using Heka 0.8
