### ISSUE TITLE
Missing Field[<field>] fields in ESJsonEncoder

### ISSUE THREAD

**Issue by mattupstate** [mozilla-services/heka#1203]
I've configured an Nginx access log decoder like so:

```toml
[api_proxy_access_log_decoder]
type = "SandboxDecoder"
filename = "lua_decoders/nginx_access.lua"

    [api_proxy_access_log_decoder.config]
    type = "nginx.access"
    user_agent_transform = true
    user_agent_conditional = true
    log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $request_time $upstream_response_time "$http_referer" "$http_user_agent"'
```

And I'm getting messages into the router that look like this:

```rst
:Timestamp: 2014-11-23 15:22:18 +0000 UTC
:Type: nginx.access
:Hostname: ip-10-80-155-196
:Pid: 0
:Uuid: 673c30fb-5e52-48b7-ad9a-7bb9670eb0b6
:Logger: api_proxy_access_log_input
:Payload:
:EnvVersion:
:Severity: 7
:Fields:
    | name:"upstream_response_time" type:double value:0.003 representation:"s"
    | name:"remote_user" type:string value:"-"
    | name:"user_agent_browser" type:string value:"Chrome"
    | name:"http_referer" type:string value:"-"
    | name:"body_bytes_sent" type:double value:731 representation:"B"
    | name:"remote_addr" type:string value:"10.80.96.4" representation:"ipv4"
    | name:"user_agent_os" type:string value:"Macintosh"
    | name:"user_agent_version" type:double value:38
    | name:"status" type:double value:200
    | name:"request" type:string value:"GET / HTTP/1.1"
    | name:"request_time" type:double value:0.003 representation:"s"
```

But my ElasticSearch encoder and output...

```toml
[es_encoder]
type = "ESJsonEncoder"
index = "%{Type}-%{2006.01.02}"
es_index_from_timestamp = true
type_name = "%{Type}"
fields = ["Timestamp", "Type", "Hostname", "Uuid", "Logger", "Severity", "Fields"]

[es_output]
type = "ElasticSearchOutput"
message_matcher = "Logger == 'api_proxy_access_log_input' || Logger == 'api_proxy_error_log_input'"
encoder = "es_encoder"
server = "http://..."
flush_interval = 5000
flush_count = 10
```

are not sending the `upstream_response_time` or `request_time` to ElasticSearch. The ES message source looks like:

```json
{
  "Timestamp": "2014-11-23T15:22:18.000Z",
  "Type": "nginx.access",
  "Hostname": "ip-10-80-155-196",
  "Uuid": "e1e5cc08-94a2-42dc-a80c-c1c3db4d9277",
  "Logger": "api_proxy_access_log_input",
  "Severity": 7,
  "remote_user": "-",
  "user_agent_browser": "Chrome",
  "http_referer": "-",
  "body_bytes_sent": 731,
  "remote_addr": "10.80.96.4",
  "user_agent_os": "Macintosh",
  "user_agent_version": 38,
  "status": 200,
  "request": "GET / HTTP/1.1"
}
```

And for what its worth, the `upstream_response_time` and `request_time` fields do come through if I change to an InfluxDB encoder and output.
