### ISSUE TITLE
error messages in lua decoders

### ISSUE THREAD

**Issue by gigaroby** [mozilla-services/heka#1209]
whenever my lua decoder encounters a problem the error message shown is always the same:

```
2014/11/28 16:31:40 Decoder 'LogfileError-BunyanDecoder' error: FATAL: process_message() /usr/share/heka/lua_decoders/bunyan.lua:105: inject_message() could not encode protobuf -
```

I already encountered this error message a few times and evey time it was related to something entirely different (missing message fields, no support for nested structures, ...)
It takes a lot of guessing to really understand what the problem is...

In this case the error is triggered with a json file that has very long lines (up to 40k characters).
At first I thought it might have been a problem with cjson but I could not find any evidence of upper bounds on the length of strings passed to cjson.

Am I missing something obvious here?

Decoder:

``` lua
--[[
bunyan.lua decodes bunyan messages into heka structures
params:
  - type: type of the message (e.g.: webserver.access)
  - exclude: space separated list of keys that will not be included in the final message
--]]

require "string"

local date_time = require "date_time"
local json = require "cjson"
local table = require "table"

local bunyan_to_syslog = {
    [20] = 7, -- DEBUG
    [30] = 6, -- INFO
    [40] = 4, -- WARNING
    [50] = 3, -- ERROR
    [60] = 1 -- CRITICAL, FATAL
}

function flatten(from)
    local b = {}
    flatten_rec(from, b, "")
    return b
end

function flatten_rec(from, to, prefix)
    for k, v in pairs(from) do
        local flattened_key = prefix
        if flattened_key == "" then
            flattened_key = k
        else
            flattened_key = flattened_key .. "." .. k
        end

        if type(v) == "table" then
            flatten_rec(v, to, flattened_key)
        else
            to[flattened_key] = v
        end
    end
end

function from_fields(t, old, new)
    t[new] = t.Fields[old]
    t.Fields[old] = nil
end

function to_syslog(t, old, new)
    t[new] = bunyan_to_syslog[t.Fields[old]]
    t.Fields[old] = nil
end

function to_int(t, old, new)
    t[new] = tonumber(t.Fields[old])
    t.Fields[old] = nil
end


function to_timestamp(t, old, new)
    local ti = date_time.rfc3339:match(t.Fields[old])
    t[new] = date_time.time_to_ns(ti)
    t.Fields[old] = nil
end

local msg_type = read_config("type")
local exclude_list = read_config("exclude")

function process_message ()
    local log = read_message("Payload") .. "}" -- append a '}' char as '}\n' is used as split pattern and thus removed
    local success, fields = pcall(json.decode, log)
    if not success then return -1 end
    local fields = flatten(fields)

    for s in string.gmatch(exclude_list, "%S+") do
        fields[s] = nil
    end

    msg = {
        Fields = fields,
        Type = msg_type
    }

    from_fields(msg, "name", "Logger")
    from_fields(msg, "msg", "Payload")
    to_int(msg, "pid", "Pid")
    to_syslog(msg, "level", "Severity")
    to_timestamp(msg, "time", "Timestamp")
    inject_message(msg)
    return 0
end
```

Config example:

``` toml
[WebserverLogfile]
type="LogstreamerInput"
log_directory="/var/log/supervisor"
file_match='webserver-stdout\.log'
decoder="BunyanDecoder"
hostname="mywebserver"
parser_type="regexp"
delimiter='}\\n'
delimiter_location="end"

[BunyanDecoder]
type="SandboxDecoder"
filename="lua_decoders/bunyan.lua"
    [BunyanDecoder.config]
    type="webserver.access"
    exclude="field1 field2"
```
