### ISSUE TITLE
support for dictionnaries in config

### ISSUE THREAD

**Issue by djamelfel** [mozilla-services/heka#1246]
I think it will be very useful, if heka could support reading dictionaries in config file.

So we could have something like:
```toml
[custom_filter]
    [custom_filter.config]
        [custom_filter.config.field1]
        label = "label_1"
        value = 1548
        [custom_filter.config.field2]
        name = "label_2"
        value = 454
```
