### ISSUE TITLE
Panic on shutdown (decoder) close of closed channel

### ISSUE THREAD

**Issue by trink** [mozilla-services/heka#1463]
```toml
[FHR]
type = "LogstreamerInput"
log_directory = "/work/git/misc-heka/fhr"
file_match = 'fftestswitch\.txt'
decoder = "JsonDecoder"

[JsonDecoder]
type = "SandboxDecoder"
filename = "ffdecoder.lua"
```

2015/04/03 07:30:37 Shutdown initiated.
2015/04/03 07:30:37 Stop message sent to input 'FHR'
2015/04/03 07:30:37 Waiting for decoders shutdown
panic: close of closed channel

goroutine 1 [running]:
github.com/mozilla-services/heka/pipeline.Run(0xc208098000)
	/work/git/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/pipeline_runner.go:321 +0x2085
main.main()
	/work/git/heka/build/heka/src/github.com/mozilla-services/heka/cmd/hekad/main.go:191 +0x12a6
