### ISSUE TITLE
LogstreamerInput cannot take a relative path for log_directory

### ISSUE THREAD

**Issue by trink** [mozilla-services/heka#1498]
Setting `log_directory = "."` will fail to find any files in the directory
``` toml
[LogstreamerInput]
log_directory = "."
file_match = 'auth\.log'
```
