### ISSUE TITLE
Update the sandbox module_directory to allow for multiple paths

### ISSUE THREAD

**Issue by trink** [mozilla-services/heka#1525]
We should be able to do this in a non breaking way.
`module_directory = "/opt/foo;/opt/foo1"`
would expand to a lua_path of
"/opt/foo/?.lua;/opt/foo1/?.lua"
and a lua_cpath (on Unix) of
"/opt/foo/?.so;/opt/foo1/?.so"

The other option is to allow the config to individually specify the full path and cpath directly.

**Comment by davidbirdsong** [comment]
was just about to open a ticket for this.

the main thing that's messing me up is, i want to be able to require heka-shipped modules (from lua_sandbox project) and then require ours. so the thing that we'd benefit the most from is to append to the compiled-in path.

**Comment by davidbirdsong** [comment]
for the non-breaking part, what about two new config lines that, if present, override ``module_directory```?

```toml
lua_path = "/tmp/lua_files" # expands to /tmp/lua_files/?.lua
lua_cpath = "/tmp/lua_cfiles" # expands to /tmp/lua_cfiles/?.so
```

I'm not tied to the names, but this gets closer to normal lua include path semantics.
