### ISSUE TITLE
Issue with apache log parsing with a custom format string

### ISSUE THREAD

**Issue by Xe** [mozilla-services/heka#1548]
I am trying to get heka to parse an apache log with a nonstandard format:

```toml
[apache]
type = "LogstreamerInput"
log_directory = "/home/cdodrill/"
file_match = 'access\.log'
decoder = "ApacheLogDecoder"

[ApacheLogDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/apache_access.lua"

[ApacheLogDecoder.config]
type = "common"
user_agent_transform = false
log_format = '%h %D %{wallclock_time}i %{cpu_user_time}i %{cpu_system_time}i %t %u "%r" %s %b "%{Referer}i" "%{User-Agent}i" "%{X-Forwarded-For}i"'
```

A (stripped) log line looks like this:

```
127.0.0.1 40312 49093 52003 0 [21/May/2015:16:47:54 -0700] "POST /api/xmlrpc/client.php HTTP/1.0" 200 466 "-" "aXMLRPC" "8.3.56.98"
```

Heka will fail with:

```
2015/05/21 17:20:09 Decoder 'apache-ApacheLogDecoder-1' error: Failed parsing:  payload: ...
```

But with no easy reason as to why, and my attempts to isolate and test the dependencies were unsuccessful.

Is there something I am missing here?
