### ISSUE TITLE
Process Input v.10 Delay/Hang symptoms

### ISSUE THREAD

**Issue by Tripleray** [mozilla-services/heka#1620]
Hey all,
	&nbsp;&nbsp;&nbsp;&nbsp;I believe I've encountered a small bug with Process Input on the v.10.0.b0 binary release. It should    be pretty easy to re-produce. The symptoms are the Heka ProcessInput plugin either hangs or gets an odd delay when executing the command with the ts binary.  Whats weird about it is if you remove the third command (The ts binary) the problem doesn't appear to happen. After discussing on the Heka IRC. It seems that there could be a possible race condition somewhere. This only seems to happen on the v.10 release. I've tested on v0.9 and its completely fine. (OS: Linux Ubuntu Vivid)
	&nbsp;&nbsp;&nbsp;&nbsp;Below is an example of the TOML configuration file. As well as the output from the v0.9 release and the output of the v.10 release. Letting it run two ticker_intervals.

**Expected (v.0.9)**
	*2015/07/16 15:24:14 Thu Jul 16 15:24:14 -0400 2015 /dev/mapper/ubuntu--vg-root 303223168 20919736 266877488   8% /*

*2015/07/16 15:24:14 Thu Jul 16 15:24:14 -0400 2015 tmpfs                         1982520      376   1982144   1% /dev/shm*

*2015/07/16 15:24:14 Thu Jul 16 15:24:14 -0400 2015 /dev/sda1                      240972   107778    120753  48% /boot*

*2015/07/16 15:24:17 Thu Jul 16 15:24:17 -0400 2015 /dev/mapper/ubuntu--vg-root 303223168 20919736 266877488   8% /*

*2015/07/16 15:24:17 Thu Jul 16 15:24:17 -0400 2015 tmpfs                         1982520      376   1982144   1% /dev/shm*

*2015/07/16 15:24:17 Thu Jul 16 15:24:17 -0400 2015 /dev/sda1                      240972   107778    120753  48% /boot*

**Actual (v.0.10)**
	*2015/07/16 15:33:08 Thu Jul 16 15:33:08 -0400 2015 /dev/mapper/ubuntu--vg-root 303223168 20969536 266827688   8% /*

```toml
[ProcessInput]
	stdout = true
	stderr = false
	splitter = "TokenSplitter"
	ticker_interval = 3

[ProcessInput.command.0]
	bin = "/bin/df"
[ProcessInput.command.1]
	bin = "/bin/grep"
	args = ["/dev/"]
[ProcessInput.command.2]
	 bin = "/usr/bin/ts"
	 args = ["%a %b %d %T %z %Y"]
[PayloadEncoder]
	append_newlines = true
[LogOutput]
	encoder = "PayloadEncoder"
	message_matcher = "TRUE"
```

**Comment by imormo** [comment]
It might come from the exist status implementation in v0.10. I will check.

**Comment by simonpasquier** [comment]
I can reproduce the issue with a simpler configuration (eg no piped commands):

```toml
[ProcessInput]
    stdout = true
    stderr = false
    splitter = "TokenSplitter"
    ticker_interval = 3

[ProcessInput.command.0]
    bin = "/bin/df"

[PayloadEncoder]
    append_newlines = true

[LogOutput]
    encoder = "PayloadEncoder"
    message_matcher = "TRUE"
```

Output with Heka 0.10:
```
2015/07/30 09:06:41 Filesystem               1K-blocks    Used Available Use% Mounted on
```
And it stops there, no other log after ticker_interval has elapsed.

Output with Heka 0.9.2:
```
2015/07/30 09:13:05 Filesystem               1K-blocks    Used Available Use% Mounted on

2015/07/30 09:13:05 /dev/mapper/os-root       15350768 4019252  10528720  28% /

2015/07/30 09:13:05 none                             4       0         4   0% /sys/fs/cgroup

2015/07/30 09:13:05 udev                       1271676       4   1271672   1% /dev

2015/07/30 09:13:05 tmpfs                       256608     612    255996   1% /run

2015/07/30 09:13:05 none                          5120      44      5076   1% /run/lock

2015/07/30 09:13:05 none                       1283020   60868   1222152   5% /run/shm

2015/07/30 09:13:05 none                        102400       0    102400   0% /run/user

2015/07/30 09:13:05 /dev/vda3                   200672   39188    151264  21% /boot
```
