### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by looatgb** [mozilla-services/heka#1626]
Hi,

I've got a problem with high CPU usage (50%-99% depending on configuration) with heka. From the posts I've read about heka, this is not the way it's supposed to be.

My hekad is running 5x (LogstreamerInput +RegexSplitter + SandboxDecoder) + ESJsonEncoder + ESOutput.

Logstreamers initially scan logs of size 20GB (and I can understand increased load during that time), however after parseing initial data, hekad goes IDLE, yet it still consumes constantly more than 50% CPU. I've got 2x2Ghz core - hekad consumes 50% of each core.

My machine is on Red Hat Enterprise Linux 6. I am running measurements with `top` command (and Shift+I to switch to "% per core" view).

My hekad config:

```toml
[hekad]
max_message_size = 26214400
maxprocs = 1
poolsize = 1

#################
# Main Log      #
#################

[AcmeMainLogInput]
type = "LogstreamerInput"
oldest_duration = "8640h"
log_directory = "/var/log/acme"
file_match = 'serv-(?P<Hostname>[^/]+)/(?P<Dev>DEV-\d+-[^_]+)_Main\.log-?(?P<Seq>\d*)'
priority = ["Hostname", "Dev", "Seq"]
differentiator = ["Hostname", "|", "Dev", "|Main"]
splitter = "AcmeMainLogSplitter"
decoder = "AcmeMainLogDecoder"

    [AcmeMainLogInput.translation.Seq]
    missing = 99999999

[AcmeMainLogSplitter]
type = "RegexSplitter"
delimiter = '(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2} DEVICE:.*)\n'
delimiter_eol = false

[AcmeMainLogDecoder]
type = "SandboxDecoder"
filename = "/etc/heka/lua_decoders/acme_main_log.lua"
memory_limit = 26214400
output_limit = 26214400
instruction_limit = 1500000
    
    [AcmeMainLogDecoder.config]
    message_type = "acme_main"
    payload_keep = true
    env_version = "prod"

#################
# N Log         #
#################

[AcmeCommLogInput]
type = "LogstreamerInput"
oldest_duration = "8640h"
log_directory = "/var/log/acme"
file_match = 'serv-(?P<Hostname>[^/]+)/(?P<Dev>DEV-\d+-[^_]+)_COMM_(?P<System>[^.]+)\.log-?(?P<Seq>\d*)'
priority = ["Hostname", "Dev", "System", "Seq"]
differentiator = ["Hostname", "|", "Dev", "|COMM_", "System"]
splitter = "AcmeCommLogSplitter"
decoder = "AcmeCommLogDecoder"

    [AcmeCommLogInput.translation.Seq]
    missing = 99999999

[AcmeCommLogSplitter]
type = "RegexSplitter"
delimiter = '(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2} \S+ [<-][->] \S+.*)\n'
delimiter_eol = false

[AcmeCommLogDecoder]
type = "SandboxDecoder"
filename = "/etc/heka/lua_decoders/acme_comm_log.lua"
memory_limit = 26214400
output_limit = 26214400
instruction_limit = 1500000
    
    [AcmeNLogDecoder.config]
    message_type = "acme_comm"
    payload_keep = false
    env_version = "prod"

#################
# DB Log        #
#################

[AcmeDBLogInput]
type = "LogstreamerInput"
oldest_duration = "8640h"
log_directory = "/var/log/acme"
file_match = 'serv-(?P<Hostname>[^/]+)/(?P<Dev>DEV-\d+-[^_]+)_DB\.log-?(?P<Seq>\d*)'
priority = ["Hostname", "Dev", "Seq"]
differentiator = ["Hostname", "|", "Dev", "|DB"]
splitter = "AcmeDBLogSplitter"
decoder = "AcmeDBLogDecoder"

    [AcmeDBLogInput.translation.Seq]
    missing = 99999999

[AcmeDBLogSplitter]
type = "RegexSplitter"
delimiter = '(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2} DB QUERY:)\n'
delimiter_eol = false

[AcmeDBLogDecoder]
type = "SandboxDecoder"
filename = "/etc/heka/lua_decoders/acme_db_log.lua"
memory_limit = 26214400
output_limit = 26214400
instruction_limit = 1500000
    
    [AcmeDBLogDecoder.config]
    message_type = "acme_db"
    payload_keep = false
    env_version = "prod"

#################
# Error Log     #
#################

[AcmeErrorLogInput]
type = "LogstreamerInput"
oldest_duration = "8640h"
log_directory = "/var/log/acme"
file_match = 'serv-(?P<Hostname>[^/]+)/(?P<Dev>DEV-\d+-[^_]+)_Error\.log-?(?P<Seq>\d*)'
priority = ["Hostname", "Dev", "Seq"]
differentiator = ["Hostname", "|", "Dev", "|Error"]
splitter = "AcmeErrorLogSplitter"
decoder = "AcmeErrorLogDecoder"

    [AcmeErrorLogInput.translation.Seq]
    missing = 99999999

[AcmeErrorLogSplitter]
type = "RegexSplitter"
delimiter = '(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2} .+)\n'
delimiter_eol = false

[AcmeErrorLogDecoder]
type = "SandboxDecoder"
filename = "/etc/heka/lua_decoders/acme_error_log.lua"
memory_limit = 26214400
output_limit = 26214400
instruction_limit = 1500000
    
    [AcmeErrorLogDecoder.config]
    message_type = "acme_error"
    payload_keep = false
    env_version = "prod"

#################
# IO Warn Log   #
#################

[AcmeIOWarningResLogInput]
type = "LogstreamerInput"
oldest_duration = "8640h"
log_directory = "/var/log/acme"
file_match = 'serv-(?P<Hostname>[^/]+)/(?P<Dev>DEV-\d+-[^_]+)_IO_WARNING_RES\.log-?(?P<Seq>\d*)'
priority = ["Hostname", "Dev", "Seq"]
differentiator = ["Hostname", "|", "Dev", "|IO_WARNING_RES"]
splitter = "AcmeIOWarningResLogSplitter"
decoder = "AcmeIOWarningResLogDecoder"

    [AcmeIOWarningResLogInput.translation.Seq]
    missing = 99999999

[AcmeIOWarningResLogSplitter]
type = "RegexSplitter"
delimiter = '(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[+-]\d{2}:\d{2} .+)\n'
delimiter_eol = false

[AcmeIOWarningResLogDecoder]
type = "SandboxDecoder"
filename = "/etc/heka/lua_decoders/acme_io_warning_res_log.lua"
memory_limit = 26214400
output_limit = 26214400
instruction_limit = 1500000
    
    [AcmeIOWarningResLogDecoder.config]
    message_type = "acme_io_warning_res"
    payload_keep = false
    env_version = "prod"

#################
# ES Output     #
#################

[ESJsonEncoder]
index = "%{Type}"
type_name = "%{Type}"

[ElasticSearchOutput]
message_matcher = "Type =~ /^acme/"
server = "http://0.0.0.0:9200"
flush_interval = 3000
flush_count = 1
encoder = "ESJsonEncoder"

###############################
# For Debugging purposes only #
###############################

#[DashboardOutput]
#ticker_interval = 1
#address = "0.0.0.0:4352"

#[PayloadEncoder]
#append_newlines = false

#[LogOutput]
#message_matcher = "Type =~ /^acme/"
#encoder = "PayloadEncoder"
```

Example decoder (they are all similar, they just have a little diffrent patterns):

```lua
-- Acme DB Log Decoder

require 'string'
require 'table'

local timestampPattern = "(%d%d%d%d%-%d%d%-%d%dT%d%d:%d%d:%d%d[+-]%d%d:%d%d)%s+"
local headerPattern    = "DB%sQUERY:%s*\n"
local messagePattern   = "(.-)\n\n"
local grammarPattern   = timestampPattern .. headerPattern .. messagePattern
local callerPattern    = "([^:%c]-::[^:%c]-%s[^:%c]-:%d+)%s*\n*$"
local paramsPattern    = "([^%c]+)\n*$"
local loggerPattern    = "([^|]+)|([^|]+)|DB"

local payload_keep = read_config("payload_keep")
local env_version = read_config("env_version")
local msg = {
    Type = "acme_db",
    Payload = " ",
    Fields = {
        LoggedAt    = nil,
        Query       = nil,
        Params      = nil,
        Caller      = nil,
        Device      = nil,
        File        = "DB",
        EnvVersion  = env_version,
    },
    Severity = 6,
}

function process_message()
    local logger    = read_message('Logger')
    local data      = read_message('Payload')

    -- sanity check
    if data:find(grammarPattern) == nil then
        return -1
    end

    -- payload size check
    if payload_keep then
        local payloadLength = #data
        if payloadLength and payloadLength > 10000 then
            msg.Payload = "**Payload limit (10000 chars) exceded (got " .. payloadLength .. ")**"
        else
            msg.Payload = data
        end
    end

    for timestamp, message in data:gmatch(grammarPattern) do
        local body = message
        local caller = nil
        local params = nil

        for match in body:gmatch(callerPattern) do
            body    = body:gsub(callerPattern, "")
            caller  = match
        end

        for match in body:gmatch(paramsPattern) do
            body    = body:gsub(paramsPattern, "")
            params  = match
        end

        msg.Fields['LoggedAt']  = timestamp
        msg.Fields['Query']     = body
        msg.Fields['Params']    = params
        msg.Fields['Caller']    = caller
    end

    for hostname, device, system in logger:gmatch(loggerPattern) do
        msg.Hostname            = hostname
        msg.Fields['Device']    = device
    end

    inject_message(msg)
    return 0
end
```

I've had to increase the `instruction_limit` to make counting the payload lenght possible (at line `local payloadLength = #data`).

## Questions

* Why does hekad consume so much CPU?
* Is it possible to "count" the payload size more efficently?
* How does poolsize affect CPU/Memory usage?
* Does `poolsize = 2` mean hekad will process 2 messages at the same time (meaning 2x CPU/Memory usage?)
* Does `poolsize = 2` mean hekad will process 2 messages TOTAL, or 2 messages "per input"?
* Are there any tools/config options to make sure hekad is running at 2-5% CPU load? (I prefer heka process the message longer, but consume less CPU at any time)
* Any other optimalizations I could do?
