### ISSUE TITLE
Why InChanCapacity value is 2 in plugin elasticsearch, not 50? How to setup ? 

### ISSUE THREAD

**Issue by swan-go** [mozilla-services/heka#1726]
## heka config as blow:

```toml
[hekad]
maxprocs = 16
poolsize = 2000
plugin_chansize = 50

[RedisInput]
address = "192.168.0.11:6389"
password = "aaa"
key = "heka-test"
batch_count = 200

[ESJsonEncoder]
index = "logstash-default-%{Type}-%{%Y.%m.%d}"
es_index_from_timestamp = true
type_name = "%{Type}"
    [ESJsonEncoder.field_mappings]
    Timestamp = "@timestamp"
    Severity = "level"

[ElasticSearchOutput]
message_matcher = "TRUE"
server = "http://192.168.0.12:8873"
encoder = "ESJsonEncoder"
flush_interval = 2000
flush_count = 100

[ElasticSearchOutput.buffering]
        max_file_size = 868435456  # 856MiB
        max_buffer_size = 1073741824  # 1GiB
        full_action = "block"   # drop
        cursor_update_count = 100

[Dashboard]
type = "DashboardOutput"
address = "0.0.0.0:4354"
ticker_interval = 5
static_directory = "/opt/heka/dasher"

```

## heka dashboard as blow

```go

ElasticSearchOutput

Properties
Name	Value
DropMessageCount	6,400
InChanCapacity	2
InChanLength	0
LeakCount	0
MatchAvgDuration	191 ns
MatchChanCapacity	50
MatchChanLength	0
SentMessageCount	  2,053,998

 Dashboard
Properties
Name	Value
InChanCapacity	50
InChanLength	0
LeakCount	0
MatchAvgDuration	1,303 ns
MatchChanCapacity	50
MatchChanLength	0

```
