### ISSUE TITLE
Importing config files aka /etc/heka.d/ support

### ISSUE THREAD

**Issue by Seldaek** [mozilla-services/heka#407]
It'd be great for puppet configurations to have a way to include/merge many toml files into one at the heka config level. Proposal for the config:

``` toml
[hekad]
includes = ["/etc/heka.d/*.toml", "/home/foo/heka/*"]
```

This implies includes are a list of glob patterns.

Maybe it should be in the global space and not within hekad though.
