### ISSUE TITLE
New PayloadJsonDecoder parser_type for direct message input

### ISSUE THREAD

**Issue by Seldaek** [mozilla-services/heka#519]
It would be great if there was a way to directly absorb json data if the data is already formatted with the heka message format. Here is an example for clarity:

``` toml
[foo]
type = "ProcessInput"
ticker_interval = 1
parser_type = "token"
decoder = "json_decoder"

[foo.command.0]
bin = "...."

[json_decoder]
type = "PayloadJsonDecoder"
parser_type = "message.json"
```

This would work if the binary being called outputs stuff like:

``` json
{"Timestamp": "...", "Type": "...", "Fields": {"foo":"bar", "count": 10}}
```

The good thing is json has int/string types so you would already get that without having to specify the field types (i.e. #512), e.g. the count field here would remain an int. The bad thing is it's lacking a date type so we just need to parse whatever is in Timestamp as a date somehow. I'm not sure what Go offers in that domain, but if needed I assume we can restrict them like TOML does, i.e. `Datetimes are ISO 8601 dates, but only the full zulu form is allowed.`
