### ISSUE TITLE
Default LogfileInput -> FileOutput inserts extra newlines

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/heka#596]
The simple file pass through config below, from http://russell.ballestrini.net/heka-world/, works, but the output file will have an extra newline between every line of the file. This is because the default TokenParser used by the LogfileInput does not remove the "\n" delimiter from each parsed record, but the FileOutput still appends one to each line. It seems to me that we should be consistent here. I'd lean towards removing the appended newline on the output side and leaving it up to the generator of the text data to make sure newlines are in place. 

``` toml
[hello_heka_input_log]
type = "LogfileInput"
logfile = "/tmp/input.log"

[hello_heka_output_log]
type = "FileOutput"
message_matcher = "TRUE"
path = "/tmp/output.log"
prefix_ts = true
perm = "664"
```
