### ISSUE TITLE
Allow inclusion of specific fields only in ElasticSearch JSON encodings

### ISSUE THREAD

**Issue by lyrixx** [mozilla-services/heka#873]
I could be very nice to be able to select **Fields** synced from heka to elastic search.
Right now we can only select properties from Heka message, but not sub Fields, from custom fields.

My payload looks like this:

```
        Timestamp: 2014-05-30 13:43:04 +0000 UTC
        Type: connect
        Hostname: connect.product.localhost
        Pid: 0
        UUID: 
        Logger: app
        Payload: {"level_name":"ERROR","datetime":{"date":"2014-05-30 13:43:04","timezone_type":3,"timezone":"UTC"},"channel":"app","extra":{"referer":"http:\/\/connect.product.localhost\/app_dev.php\/login","referrer":"http:\/\/connect.product.localhost\/app_dev.php\/login","server":"connect.product.localhost","http_method":"GET","url":"\/app_dev.php\/sln-customize.js","ip":"127.0.0.1"},"level":400,"context":{},"message":"coucou"}

        EnvVersion: 
        Severity: 3
        Fields: [name:"message" value_type:STRING representation:"" value_string:"coucou"  name:"payload_type" value_type:STRING representation:"file-extension" value_string:"txt"  name:"payload_name" value_type:STRING representation:"" value_string:"" ]

```

My config:

```
[output_elasticsearch]
type = "ElasticSearchOutput"
message_matcher = "Type =~ /.*/"
cluster = "elasticsearch"
index = "heka"
type_name = "%{Type}-%{Logger}"
server = "http://localhost:9200"
flush_interval = 1000 # in ms
flush_count = 10
fields = [ "Timestamp", "Type", "Logger", "Severity", "Payload", "Hostname", "Fields"]
```

And I would like something like

``` diff
- fields = [ "Timestamp", "Type", "Logger", "Severity", "Payload", "Hostname", "Fields"]
+ fields = [ "Timestamp", "Type", "Logger", "Severity", "Payload", "Hostname", "Fields[message]"]
```
